### ISSUE TITLE
Overreacting

### ISSUE THREAD

**Issue by sn0w** [selfagency/microsoft-drop-ice#132]
You people do realize that microsoft didn't even "buy" GitHub yet, right?
The acquisition is expected to close by the end of the year.
This whole repository is an emtpy and unjustified threat to a - so far - unrelated company.

**Comment by selfagency** [comment]
You do realize that by the time Microsoft and GitHub finalize the acquisition, the value of its multi-billion dollar purchase could plummet because of users leaving the platform en mass right? No. No. You don't realize that.

**Comment by jerriep** [comment]
@selfagency Since you chose the way of the coward on #111, I'll respond here:

> you made it clear that you are not here for the benefit of refugees, asylum seekers, and undocumented immigrants, but as a concern troll.

Given that I'm probably the only one between all of you who bothers to visit refugees in detention centres and do something tangible to make their lives better, that is a bit of a silly statement. How many refugees have you visited? When I suggested it your immediate response was that you will not be allowed to. You did not even bother to find out.

Why don't you just stop the charade and admit this is politically motived? I care much more about the refugees that you do with your fake outrage.

**Comment by sn0w** [comment]
@selfagency 

>  the value of its multi-billion dollar purchase could plummet

no it won't.
GitHub has more than 40 million users.
There is always enough data left to make this deal profitable.

**Comment by selfagency** [comment]
@jerriep My father is a refugee and I have been fighting on behalf of asylum seekers for the last decade, so kindly blow it out your ass. The most tangible thing we can do to help refugees, asylum seekers, and undocumented immigrants in this country is to abolish ICE, and the road to that victory begins with making them untouchables that no one will work with. Thanks again for your concern trolling.
